[package]
name = "acerola_jam_0"
version = "0.1.0"
edition = "2021"

[profile.dev.package.'*']
opt-level = 3

[dependencies]
gamepads = "0.1.6"
macroquad = { version = "0.4.5", features = ["audio"] }
macroquad-tiled = "0.2.1"
tiled = { version = "0.11.2", features = ["wasm"] }
